# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: booking
  username: postgres
  password: password
test:
  <<: *default
  database: booking_test
  username: postgres
  password: password
production:
  <<: *default
  database: d2sf9ri4tqum4c
  username: zkmukourargoeo
  password: 5d598b4442e4a397fc6d6a7455d6fe7e00b80d016ed2381c207fb27dbb1bd89a
  port: 5432
  url: postgres://zkmukourargoeo:5d598b4442e4a397fc6d6a7455d6fe7e00b80d016ed2381c207fb27dbb1bd89a@ec2-54-217-204-34.eu-west-1.compute.amazonaws.com:5432/d2sf9ri4tqum4c



